# Generated by Django 4.0.4 on 2022-08-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_remove_pelicula_pelicula_pelicula_nombre_and_more'),
    ]
