# Generated by Django 4.0.4 on 2022-08-02 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_app', '0004_pelicula_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='pelicula',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_portada'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
